<?php
/**
 * CloudPosCheckApiTest
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace QsrAutomations\Api;

use \QsrAutomations\Api\Configuration;
use \QsrAutomations\Api\ApiClient;
use \QsrAutomations\Api\ApiException;
use \QsrAutomations\Api\ObjectSerializer;

/**
 * CloudPosCheckApiTest Class Doc Comment
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CloudPosCheckApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cloudPosCheckAddCheck
     *
     * .
     *
     */
    public function testCloudPosCheckAddCheck()
    {
    }

    /**
     * Test case for cloudPosCheckAddCourseToCheck
     *
     * .
     *
     */
    public function testCloudPosCheckAddCourseToCheck()
    {
    }

    /**
     * Test case for cloudPosCheckAddItemsToCourse
     *
     * .
     *
     */
    public function testCloudPosCheckAddItemsToCourse()
    {
    }

    /**
     * Test case for cloudPosCheckAddPaymentStateToCourse
     *
     * .
     *
     */
    public function testCloudPosCheckAddPaymentStateToCourse()
    {
    }

    /**
     * Test case for cloudPosCheckAddPaymentStatesToCheck
     *
     * .
     *
     */
    public function testCloudPosCheckAddPaymentStatesToCheck()
    {
    }

    /**
     * Test case for cloudPosCheckBumpCheck
     *
     * .
     *
     */
    public function testCloudPosCheckBumpCheck()
    {
    }

    /**
     * Test case for cloudPosCheckBumpCourseOnCheck
     *
     * .
     *
     */
    public function testCloudPosCheckBumpCourseOnCheck()
    {
    }

    /**
     * Test case for cloudPosCheckCancelAllCoursesInCheck
     *
     * .
     *
     */
    public function testCloudPosCheckCancelAllCoursesInCheck()
    {
    }

    /**
     * Test case for cloudPosCheckCancelCourseInCheck
     *
     * .
     *
     */
    public function testCloudPosCheckCancelCourseInCheck()
    {
    }

    /**
     * Test case for cloudPosCheckCancelItemInCourse
     *
     * .
     *
     */
    public function testCloudPosCheckCancelItemInCourse()
    {
    }

    /**
     * Test case for cloudPosCheckDeleteCheck
     *
     * .
     *
     */
    public function testCloudPosCheckDeleteCheck()
    {
    }

    /**
     * Test case for cloudPosCheckDeleteCourseFromCheck
     *
     * .
     *
     */
    public function testCloudPosCheckDeleteCourseFromCheck()
    {
    }

    /**
     * Test case for cloudPosCheckFastTrackCheck
     *
     * .
     *
     */
    public function testCloudPosCheckFastTrackCheck()
    {
    }

    /**
     * Test case for cloudPosCheckFastTrackCourse
     *
     * .
     *
     */
    public function testCloudPosCheckFastTrackCourse()
    {
    }

    /**
     * Test case for cloudPosCheckFastTrackItemInCourse
     *
     * .
     *
     */
    public function testCloudPosCheckFastTrackItemInCourse()
    {
    }

    /**
     * Test case for cloudPosCheckGetCheckByCheckNumber
     *
     * .
     *
     */
    public function testCloudPosCheckGetCheckByCheckNumber()
    {
    }

    /**
     * Test case for cloudPosCheckUpdateCheck
     *
     * .
     *
     */
    public function testCloudPosCheckUpdateCheck()
    {
    }

    /**
     * Test case for cloudPosCheckUpdateCourse
     *
     * .
     *
     */
    public function testCloudPosCheckUpdateCourse()
    {
    }

    /**
     * Test case for cloudPosCheckUpdateCoursesInCheck
     *
     * .
     *
     */
    public function testCloudPosCheckUpdateCoursesInCheck()
    {
    }

    /**
     * Test case for cloudPosCheckUpdateItemInCourse
     *
     * .
     *
     */
    public function testCloudPosCheckUpdateItemInCourse()
    {
    }
}
