<?php
/**
 * GuestBookApiTest
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace QsrAutomations\Api;

use \QsrAutomations\Api\Configuration;
use \QsrAutomations\Api\ApiClient;
use \QsrAutomations\Api\ApiException;
use \QsrAutomations\Api\ObjectSerializer;

/**
 * GuestBookApiTest Class Doc Comment
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GuestBookApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for guestBookAddGuest
     *
     * .
     *
     */
    public function testGuestBookAddGuest()
    {
    }

    /**
     * Test case for guestBookAddGuestToCompanyGuestBook
     *
     * .
     *
     */
    public function testGuestBookAddGuestToCompanyGuestBook()
    {
    }

    /**
     * Test case for guestBookDeleteGuest
     *
     * .
     *
     */
    public function testGuestBookDeleteGuest()
    {
    }

    /**
     * Test case for guestBookDeleteGuestInCompanyGuestBook
     *
     * .
     *
     */
    public function testGuestBookDeleteGuestInCompanyGuestBook()
    {
    }

    /**
     * Test case for guestBookGetGuestUpdatesForCompany
     *
     * .
     *
     */
    public function testGuestBookGetGuestUpdatesForCompany()
    {
    }

    /**
     * Test case for guestBookGetGuests
     *
     * .
     *
     */
    public function testGuestBookGetGuests()
    {
    }

    /**
     * Test case for guestBookPatchGuest
     *
     * .
     *
     */
    public function testGuestBookPatchGuest()
    {
    }

    /**
     * Test case for guestBookPatchGuestInCompanyGuestBook
     *
     * .
     *
     */
    public function testGuestBookPatchGuestInCompanyGuestBook()
    {
    }

    /**
     * Test case for guestBookSearchGuestBook
     *
     * .
     *
     */
    public function testGuestBookSearchGuestBook()
    {
    }
}
