<?php
/**
 * OperatingPeriodApiTest
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace QsrAutomations\Api;

use \QsrAutomations\Api\Configuration;
use \QsrAutomations\Api\ApiClient;
use \QsrAutomations\Api\ApiException;
use \QsrAutomations\Api\ObjectSerializer;

/**
 * OperatingPeriodApiTest Class Doc Comment
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OperatingPeriodApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for operatingPeriodApplyOperatingInfoTemplate
     *
     * .
     *
     */
    public function testOperatingPeriodApplyOperatingInfoTemplate()
    {
    }

    /**
     * Test case for operatingPeriodGetOperatingInfo
     *
     * .
     *
     */
    public function testOperatingPeriodGetOperatingInfo()
    {
    }

    /**
     * Test case for operatingPeriodGetOperatingPeriodByDate
     *
     * .
     *
     */
    public function testOperatingPeriodGetOperatingPeriodByDate()
    {
    }
}
