<?php
/**
 * WebAheadApiTest
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace QsrAutomations\Api;

use \QsrAutomations\Api\Configuration;
use \QsrAutomations\Api\ApiClient;
use \QsrAutomations\Api\ApiException;
use \QsrAutomations\Api\ObjectSerializer;

/**
 * WebAheadApiTest Class Doc Comment
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebAheadApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for webAheadAddWebAhead
     *
     * Add a WebAhead.
     *
     */
    public function testWebAheadAddWebAhead()
    {
    }

    /**
     * Test case for webAheadArrive
     *
     * Arrive a WebAhead.
     *
     */
    public function testWebAheadArrive()
    {
    }

    /**
     * Test case for webAheadArriveGlobal
     *
     * Arrive a WebAhead.
     *
     */
    public function testWebAheadArriveGlobal()
    {
    }

    /**
     * Test case for webAheadCancel
     *
     * Cancel a WebAhead.
     *
     */
    public function testWebAheadCancel()
    {
    }

    /**
     * Test case for webAheadCancelGlobal
     *
     * Cancels the by confirmation number..
     *
     */
    public function testWebAheadCancelGlobal()
    {
    }

    /**
     * Test case for webAheadDisable
     *
     * .
     *
     */
    public function testWebAheadDisable()
    {
    }

    /**
     * Test case for webAheadEnable
     *
     * .
     *
     */
    public function testWebAheadEnable()
    {
    }

    /**
     * Test case for webAheadGet
     *
     * Get a WebAhead.
     *
     */
    public function testWebAheadGet()
    {
    }

    /**
     * Test case for webAheadGetWaitListStatus
     *
     * Get wait list status and quote for web ahead based on party size..
     *
     */
    public function testWebAheadGetWaitListStatus()
    {
    }

    /**
     * Test case for webAheadGetWaitListStatusForSites
     *
     * Get wait list status and quote for web ahead based on party size, for a list of sites.
     *
     */
    public function testWebAheadGetWaitListStatusForSites()
    {
    }

    /**
     * Test case for webAheadGetWebAheadGlobal
     *
     * Gets the web ahead..
     *
     */
    public function testWebAheadGetWebAheadGlobal()
    {
    }

    /**
     * Test case for webAheadUpdateWebAheadGlobalPartial
     *
     * Updates the web ahead partial by confirmation number..
     *
     */
    public function testWebAheadUpdateWebAheadGlobalPartial()
    {
    }

    /**
     * Test case for webAheadUpdateWebAheadPartial
     *
     * Update a WebAhead.
     *
     */
    public function testWebAheadUpdateWebAheadPartial()
    {
    }
}
