<?php
/**
 * QsrAutomationsDineTimeContractsWebAheadTypesIWaitListStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace QsrAutomations\Api\Model;

use \ArrayAccess;

/**
 * QsrAutomationsDineTimeContractsWebAheadTypesIWaitListStatus Class Doc Comment
 *
 * @category    Class
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsDineTimeContractsWebAheadTypesIWaitListStatus implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'QsrAutomations.DineTime.Contracts.WebAhead.Types.IWaitListStatus';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'site_uid' => 'string',
        'web_ahead_status_id' => 'int',
        'web_ahead_status' => 'string',
        'quote' => '\QsrAutomations\Api\Model\QsrAutomationsDineTimeContractsWebAheadTypesIQuote',
        'number_waiting_visits' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'site_uid' => null,
        'web_ahead_status_id' => 'int32',
        'web_ahead_status' => null,
        'quote' => null,
        'number_waiting_visits' => 'int32'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'site_uid' => 'SiteUID',
        'web_ahead_status_id' => 'WebAheadStatusId',
        'web_ahead_status' => 'WebAheadStatus',
        'quote' => 'Quote',
        'number_waiting_visits' => 'NumberWaitingVisits'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'site_uid' => 'setSiteUid',
        'web_ahead_status_id' => 'setWebAheadStatusId',
        'web_ahead_status' => 'setWebAheadStatus',
        'quote' => 'setQuote',
        'number_waiting_visits' => 'setNumberWaitingVisits'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'site_uid' => 'getSiteUid',
        'web_ahead_status_id' => 'getWebAheadStatusId',
        'web_ahead_status' => 'getWebAheadStatus',
        'quote' => 'getQuote',
        'number_waiting_visits' => 'getNumberWaitingVisits'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['site_uid'] = isset($data['site_uid']) ? $data['site_uid'] : null;
        $this->container['web_ahead_status_id'] = isset($data['web_ahead_status_id']) ? $data['web_ahead_status_id'] : null;
        $this->container['web_ahead_status'] = isset($data['web_ahead_status']) ? $data['web_ahead_status'] : null;
        $this->container['quote'] = isset($data['quote']) ? $data['quote'] : null;
        $this->container['number_waiting_visits'] = isset($data['number_waiting_visits']) ? $data['number_waiting_visits'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets site_uid
     * @return string
     */
    public function getSiteUid()
    {
        return $this->container['site_uid'];
    }

    /**
     * Sets site_uid
     * @param string $site_uid
     * @return $this
     */
    public function setSiteUid($site_uid)
    {
        $this->container['site_uid'] = $site_uid;

        return $this;
    }

    /**
     * Gets web_ahead_status_id
     * @return int
     */
    public function getWebAheadStatusId()
    {
        return $this->container['web_ahead_status_id'];
    }

    /**
     * Sets web_ahead_status_id
     * @param int $web_ahead_status_id
     * @return $this
     */
    public function setWebAheadStatusId($web_ahead_status_id)
    {
        $this->container['web_ahead_status_id'] = $web_ahead_status_id;

        return $this;
    }

    /**
     * Gets web_ahead_status
     * @return string
     */
    public function getWebAheadStatus()
    {
        return $this->container['web_ahead_status'];
    }

    /**
     * Sets web_ahead_status
     * @param string $web_ahead_status
     * @return $this
     */
    public function setWebAheadStatus($web_ahead_status)
    {
        $this->container['web_ahead_status'] = $web_ahead_status;

        return $this;
    }

    /**
     * Gets quote
     * @return \QsrAutomations\Api\Model\QsrAutomationsDineTimeContractsWebAheadTypesIQuote
     */
    public function getQuote()
    {
        return $this->container['quote'];
    }

    /**
     * Sets quote
     * @param \QsrAutomations\Api\Model\QsrAutomationsDineTimeContractsWebAheadTypesIQuote $quote
     * @return $this
     */
    public function setQuote($quote)
    {
        $this->container['quote'] = $quote;

        return $this;
    }

    /**
     * Gets number_waiting_visits
     * @return int
     */
    public function getNumberWaitingVisits()
    {
        return $this->container['number_waiting_visits'];
    }

    /**
     * Sets number_waiting_visits
     * @param int $number_waiting_visits
     * @return $this
     */
    public function setNumberWaitingVisits($number_waiting_visits)
    {
        $this->container['number_waiting_visits'] = $number_waiting_visits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\QsrAutomations\Api\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\QsrAutomations\Api\ObjectSerializer::sanitizeForSerialization($this));
    }
}


