<?php
/**
 * QsrAutomationsDineTimeServerTypesTeamMemberEventContentDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace QsrAutomations\Api\Model;

use \ArrayAccess;

/**
 * QsrAutomationsDineTimeServerTypesTeamMemberEventContentDTO Class Doc Comment
 *
 * @category    Class
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsDineTimeServerTypesTeamMemberEventContentDTO implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'QsrAutomations.DineTime.Server.Types.TeamMemberEventContentDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'team_member' => '\QsrAutomations\Api\Model\QsrAutomationsDineTimeServerTypesTeamMemberSnapshotDTO',
        'stations' => '\QsrAutomations\Api\Model\QsrAutomationsDineTimeStationTypesStationSnapshotDTO[]',
        'floor_plan' => '\QsrAutomations\Api\Model\QsrAutomationsDineTimeFloorPlanTypesFloorPlanSnapshotDTO',
        'shift' => '\QsrAutomations\Api\Model\QsrAutomationsDineTimeShiftTypesShiftSnapshotDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'team_member' => null,
        'stations' => null,
        'floor_plan' => null,
        'shift' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'team_member' => 'TeamMember',
        'stations' => 'Stations',
        'floor_plan' => 'FloorPlan',
        'shift' => 'Shift'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'team_member' => 'setTeamMember',
        'stations' => 'setStations',
        'floor_plan' => 'setFloorPlan',
        'shift' => 'setShift'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'team_member' => 'getTeamMember',
        'stations' => 'getStations',
        'floor_plan' => 'getFloorPlan',
        'shift' => 'getShift'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['team_member'] = isset($data['team_member']) ? $data['team_member'] : null;
        $this->container['stations'] = isset($data['stations']) ? $data['stations'] : null;
        $this->container['floor_plan'] = isset($data['floor_plan']) ? $data['floor_plan'] : null;
        $this->container['shift'] = isset($data['shift']) ? $data['shift'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets team_member
     * @return \QsrAutomations\Api\Model\QsrAutomationsDineTimeServerTypesTeamMemberSnapshotDTO
     */
    public function getTeamMember()
    {
        return $this->container['team_member'];
    }

    /**
     * Sets team_member
     * @param \QsrAutomations\Api\Model\QsrAutomationsDineTimeServerTypesTeamMemberSnapshotDTO $team_member
     * @return $this
     */
    public function setTeamMember($team_member)
    {
        $this->container['team_member'] = $team_member;

        return $this;
    }

    /**
     * Gets stations
     * @return \QsrAutomations\Api\Model\QsrAutomationsDineTimeStationTypesStationSnapshotDTO[]
     */
    public function getStations()
    {
        return $this->container['stations'];
    }

    /**
     * Sets stations
     * @param \QsrAutomations\Api\Model\QsrAutomationsDineTimeStationTypesStationSnapshotDTO[] $stations
     * @return $this
     */
    public function setStations($stations)
    {
        $this->container['stations'] = $stations;

        return $this;
    }

    /**
     * Gets floor_plan
     * @return \QsrAutomations\Api\Model\QsrAutomationsDineTimeFloorPlanTypesFloorPlanSnapshotDTO
     */
    public function getFloorPlan()
    {
        return $this->container['floor_plan'];
    }

    /**
     * Sets floor_plan
     * @param \QsrAutomations\Api\Model\QsrAutomationsDineTimeFloorPlanTypesFloorPlanSnapshotDTO $floor_plan
     * @return $this
     */
    public function setFloorPlan($floor_plan)
    {
        $this->container['floor_plan'] = $floor_plan;

        return $this;
    }

    /**
     * Gets shift
     * @return \QsrAutomations\Api\Model\QsrAutomationsDineTimeShiftTypesShiftSnapshotDTO
     */
    public function getShift()
    {
        return $this->container['shift'];
    }

    /**
     * Sets shift
     * @param \QsrAutomations\Api\Model\QsrAutomationsDineTimeShiftTypesShiftSnapshotDTO $shift
     * @return $this
     */
    public function setShift($shift)
    {
        $this->container['shift'] = $shift;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\QsrAutomations\Api\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\QsrAutomations\Api\ObjectSerializer::sanitizeForSerialization($this));
    }
}


