<?php
/**
 * CloudPosContractBaseClassesCheckDTOCheckWithKitchenStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * CloudPosContractBaseClassesCheckDTOCheckWithKitchenStatusTest Class Doc Comment
 *
 * @category    Class */
// * @description CloudPosContractBaseClassesCheckDTOCheckWithKitchenStatus
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CloudPosContractBaseClassesCheckDTOCheckWithKitchenStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CloudPosContractBaseClassesCheckDTOCheckWithKitchenStatus"
     */
    public function testCloudPosContractBaseClassesCheckDTOCheckWithKitchenStatus()
    {
    }

    /**
     * Test attribute "courses"
     */
    public function testPropertyCourses()
    {
    }

    /**
     * Test attribute "check_number"
     */
    public function testPropertyCheckNumber()
    {
    }

    /**
     * Test attribute "guest"
     */
    public function testPropertyGuest()
    {
    }

    /**
     * Test attribute "pickup_time"
     */
    public function testPropertyPickupTime()
    {
    }
}
