<?php
/**
 * QsrAutomationsDineTimeWebAheadCommandsPatchWebAheadCommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsDineTimeWebAheadCommandsPatchWebAheadCommandTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsDineTimeWebAheadCommandsPatchWebAheadCommand
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsDineTimeWebAheadCommandsPatchWebAheadCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsDineTimeWebAheadCommandsPatchWebAheadCommand"
     */
    public function testQsrAutomationsDineTimeWebAheadCommandsPatchWebAheadCommand()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "phone_number_string"
     */
    public function testPropertyPhoneNumberString()
    {
    }

    /**
     * Test attribute "is_subscribed_to_sms_marketing"
     */
    public function testPropertyIsSubscribedToSmsMarketing()
    {
    }

    /**
     * Test attribute "is_subscribed_to_email_marketing"
     */
    public function testPropertyIsSubscribedToEmailMarketing()
    {
    }

    /**
     * Test attribute "is_subscribed_to_qsr_marketing"
     */
    public function testPropertyIsSubscribedToQsrMarketing()
    {
    }

    /**
     * Test attribute "party_size"
     */
    public function testPropertyPartySize()
    {
    }

    /**
     * Test attribute "estimated_arrival_time"
     */
    public function testPropertyEstimatedArrivalTime()
    {
    }

    /**
     * Test attribute "expand_guest"
     */
    public function testPropertyExpandGuest()
    {
    }

    /**
     * Test attribute "request_time"
     */
    public function testPropertyRequestTime()
    {
    }

    /**
     * Test attribute "site_identifier"
     */
    public function testPropertySiteIdentifier()
    {
    }

    /**
     * Test attribute "brand_uid"
     */
    public function testPropertyBrandUid()
    {
    }
}
