<?php
/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesVisitsPublicTableEventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesVisitsPublicTableEventTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesVisitsPublicTableEvent
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesVisitsPublicTableEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesVisitsPublicTableEvent"
     */
    public function testQsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesVisitsPublicTableEvent()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "event_type"
     */
    public function testPropertyEventType()
    {
    }

    /**
     * Test attribute "table_name"
     */
    public function testPropertyTableName()
    {
    }

    /**
     * Test attribute "transaction_number"
     */
    public function testPropertyTransactionNumber()
    {
    }

    /**
     * Test attribute "check_amount"
     */
    public function testPropertyCheckAmount()
    {
    }

    /**
     * Test attribute "timestamp_utc"
     */
    public function testPropertyTimestampUtc()
    {
    }
}
