<?php
/**
 * QsrAutomationsDineTimeTablesTypesTableEventContentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsDineTimeTablesTypesTableEventContentTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsDineTimeTablesTypesTableEventContent
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsDineTimeTablesTypesTableEventContentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsDineTimeTablesTypesTableEventContent"
     */
    public function testQsrAutomationsDineTimeTablesTypesTableEventContent()
    {
    }

    /**
     * Test attribute "table"
     */
    public function testPropertyTable()
    {
    }

    /**
     * Test attribute "station"
     */
    public function testPropertyStation()
    {
    }

    /**
     * Test attribute "floor_plan"
     */
    public function testPropertyFloorPlan()
    {
    }

    /**
     * Test attribute "shift"
     */
    public function testPropertyShift()
    {
    }
}
