<?php
/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenBinUsageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenBinUsageTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenBinUsage
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenBinUsageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenBinUsage"
     */
    public function testQsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenBinUsage()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "bin_id"
     */
    public function testPropertyBinId()
    {
    }

    /**
     * Test attribute "bin_name"
     */
    public function testPropertyBinName()
    {
    }

    /**
     * Test attribute "dropped"
     */
    public function testPropertyDropped()
    {
    }

    /**
     * Test attribute "minutes_per_day_period"
     */
    public function testPropertyMinutesPerDayPeriod()
    {
    }

    /**
     * Test attribute "period_end_time_local"
     */
    public function testPropertyPeriodEndTimeLocal()
    {
    }

    /**
     * Test attribute "period_end_time_utc"
     */
    public function testPropertyPeriodEndTimeUtc()
    {
    }

    /**
     * Test attribute "period_start_time_local"
     */
    public function testPropertyPeriodStartTimeLocal()
    {
    }

    /**
     * Test attribute "period_start_time_utc"
     */
    public function testPropertyPeriodStartTimeUtc()
    {
    }

    /**
     * Test attribute "system_projection"
     */
    public function testPropertySystemProjection()
    {
    }

    /**
     * Test attribute "time_stamp_local"
     */
    public function testPropertyTimeStampLocal()
    {
    }

    /**
     * Test attribute "time_stamp_utc"
     */
    public function testPropertyTimeStampUtc()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "used"
     */
    public function testPropertyUsed()
    {
    }

    /**
     * Test attribute "user_projection"
     */
    public function testPropertyUserProjection()
    {
    }

    /**
     * Test attribute "wasted"
     */
    public function testPropertyWasted()
    {
    }
}
