<?php
/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyApiServiceHostCommandsPatchVisitProximityCommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyApiServiceHostCommandsPatchVisitProximityCommandTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsEnterpriseDineTimeThirdPartyApiServiceHostCommandsPatchVisitProximityCommand
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsEnterpriseDineTimeThirdPartyApiServiceHostCommandsPatchVisitProximityCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsEnterpriseDineTimeThirdPartyApiServiceHostCommandsPatchVisitProximityCommand"
     */
    public function testQsrAutomationsEnterpriseDineTimeThirdPartyApiServiceHostCommandsPatchVisitProximityCommand()
    {
    }

    /**
     * Test attribute "site_uid"
     */
    public function testPropertySiteUid()
    {
    }

    /**
     * Test attribute "visit_uid"
     */
    public function testPropertyVisitUid()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }
}
