<?php
/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenDisplayGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenDisplayGroupTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenDisplayGroup
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenDisplayGroupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenDisplayGroup"
     */
    public function testQsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenDisplayGroup()
    {
    }

    /**
     * Test attribute "courses_active"
     */
    public function testPropertyCoursesActive()
    {
    }

    /**
     * Test attribute "display_group_id"
     */
    public function testPropertyDisplayGroupId()
    {
    }

    /**
     * Test attribute "display_group_name"
     */
    public function testPropertyDisplayGroupName()
    {
    }

    /**
     * Test attribute "items_active"
     */
    public function testPropertyItemsActive()
    {
    }

    /**
     * Test attribute "items_prepared"
     */
    public function testPropertyItemsPrepared()
    {
    }

    /**
     * Test attribute "total_forecast_prep_time"
     */
    public function testPropertyTotalForecastPrepTime()
    {
    }

    /**
     * Test attribute "timestamp_local"
     */
    public function testPropertyTimestampLocal()
    {
    }
}
