<?php
/**
 * QsrAutomationsDineTimeContractsVisitsTypesIVisitPreassignedTableTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsDineTimeContractsVisitsTypesIVisitPreassignedTableTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsDineTimeContractsVisitsTypesIVisitPreassignedTable
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsDineTimeContractsVisitsTypesIVisitPreassignedTableTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsDineTimeContractsVisitsTypesIVisitPreassignedTable"
     */
    public function testQsrAutomationsDineTimeContractsVisitsTypesIVisitPreassignedTable()
    {
    }

    /**
     * Test attribute "table_id"
     */
    public function testPropertyTableId()
    {
    }

    /**
     * Test attribute "table_name"
     */
    public function testPropertyTableName()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "is_current"
     */
    public function testPropertyIsCurrent()
    {
    }
}
