<?php
/**
 * QsrAutomationsDineTimeTableTypesTableSnapshotDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsDineTimeTableTypesTableSnapshotDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsDineTimeTableTypesTableSnapshotDTO
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsDineTimeTableTypesTableSnapshotDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsDineTimeTableTypesTableSnapshotDTO"
     */
    public function testQsrAutomationsDineTimeTableTypesTableSnapshotDTO()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "seat_count"
     */
    public function testPropertySeatCount()
    {
    }

    /**
     * Test attribute "min_seat_count"
     */
    public function testPropertyMinSeatCount()
    {
    }

    /**
     * Test attribute "max_seat_count"
     */
    public function testPropertyMaxSeatCount()
    {
    }

    /**
     * Test attribute "end_seats"
     */
    public function testPropertyEndSeats()
    {
    }

    /**
     * Test attribute "qsr_table_shape_id"
     */
    public function testPropertyQsrTableShapeId()
    {
    }

    /**
     * Test attribute "statistics"
     */
    public function testPropertyStatistics()
    {
    }
}
