<?php
/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenSpeedOfServiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenSpeedOfServiceTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenSpeedOfService
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenSpeedOfServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenSpeedOfService"
     */
    public function testQsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesKitchenSpeedOfService()
    {
    }

    /**
     * Test attribute "activity_level"
     */
    public function testPropertyActivityLevel()
    {
    }

    /**
     * Test attribute "course_name"
     */
    public function testPropertyCourseName()
    {
    }

    /**
     * Test attribute "course_number"
     */
    public function testPropertyCourseNumber()
    {
    }

    /**
     * Test attribute "course_paid_time"
     */
    public function testPropertyCoursePaidTime()
    {
    }

    /**
     * Test attribute "course_park_time"
     */
    public function testPropertyCourseParkTime()
    {
    }

    /**
     * Test attribute "course_preparation_time"
     */
    public function testPropertyCoursePreparationTime()
    {
    }

    /**
     * Test attribute "course_start_time_local"
     */
    public function testPropertyCourseStartTimeLocal()
    {
    }

    /**
     * Test attribute "course_start_time_utc"
     */
    public function testPropertyCourseStartTimeUtc()
    {
    }

    /**
     * Test attribute "course_type"
     */
    public function testPropertyCourseType()
    {
    }

    /**
     * Test attribute "course_uid"
     */
    public function testPropertyCourseUid()
    {
    }

    /**
     * Test attribute "destination"
     */
    public function testPropertyDestination()
    {
    }

    /**
     * Test attribute "destination_name"
     */
    public function testPropertyDestinationName()
    {
    }

    /**
     * Test attribute "display_group_id"
     */
    public function testPropertyDisplayGroupId()
    {
    }

    /**
     * Test attribute "fast_tracked_time"
     */
    public function testPropertyFastTrackedTime()
    {
    }

    /**
     * Test attribute "first_display_time"
     */
    public function testPropertyFirstDisplayTime()
    {
    }

    /**
     * Test attribute "first_store_time"
     */
    public function testPropertyFirstStoreTime()
    {
    }

    /**
     * Test attribute "first_tender_time"
     */
    public function testPropertyFirstTenderTime()
    {
    }

    /**
     * Test attribute "first_viewed_time"
     */
    public function testPropertyFirstViewedTime()
    {
    }

    /**
     * Test attribute "food_delivered_time"
     */
    public function testPropertyFoodDeliveredTime()
    {
    }

    /**
     * Test attribute "insert_date"
     */
    public function testPropertyInsertDate()
    {
    }

    /**
     * Test attribute "item_category"
     */
    public function testPropertyItemCategory()
    {
    }

    /**
     * Test attribute "item_cook_start_time"
     */
    public function testPropertyItemCookStartTime()
    {
    }

    /**
     * Test attribute "item_cook_time"
     */
    public function testPropertyItemCookTime()
    {
    }

    /**
     * Test attribute "item_description"
     */
    public function testPropertyItemDescription()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "item_quantity"
     */
    public function testPropertyItemQuantity()
    {
    }

    /**
     * Test attribute "item_tag_time"
     */
    public function testPropertyItemTagTime()
    {
    }

    /**
     * Test attribute "item_uid"
     */
    public function testPropertyItemUid()
    {
    }

    /**
     * Test attribute "last_bump_time"
     */
    public function testPropertyLastBumpTime()
    {
    }

    /**
     * Test attribute "last_prepared_time"
     */
    public function testPropertyLastPreparedTime()
    {
    }

    /**
     * Test attribute "last_recall_time"
     */
    public function testPropertyLastRecallTime()
    {
    }

    /**
     * Test attribute "last_total_time"
     */
    public function testPropertyLastTotalTime()
    {
    }

    /**
     * Test attribute "last_unbump_time"
     */
    public function testPropertyLastUnbumpTime()
    {
    }

    /**
     * Test attribute "modifier1_id"
     */
    public function testPropertyModifier1Id()
    {
    }

    /**
     * Test attribute "modifier2_id"
     */
    public function testPropertyModifier2Id()
    {
    }

    /**
     * Test attribute "modifier3_id"
     */
    public function testPropertyModifier3Id()
    {
    }

    /**
     * Test attribute "parent_item_number"
     */
    public function testPropertyParentItemNumber()
    {
    }

    /**
     * Test attribute "priority_status_reached"
     */
    public function testPropertyPriorityStatusReached()
    {
    }

    /**
     * Test attribute "priority_time"
     */
    public function testPropertyPriorityTime()
    {
    }

    /**
     * Test attribute "remake_time"
     */
    public function testPropertyRemakeTime()
    {
    }

    /**
     * Test attribute "rush_status_reached"
     */
    public function testPropertyRushStatusReached()
    {
    }

    /**
     * Test attribute "rush_time"
     */
    public function testPropertyRushTime()
    {
    }

    /**
     * Test attribute "server_id"
     */
    public function testPropertyServerId()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "so_s_tag"
     */
    public function testPropertySoSTag()
    {
    }

    /**
     * Test attribute "station_type"
     */
    public function testPropertyStationType()
    {
    }

    /**
     * Test attribute "table"
     */
    public function testPropertyTable()
    {
    }

    /**
     * Test attribute "terminal_number"
     */
    public function testPropertyTerminalNumber()
    {
    }

    /**
     * Test attribute "time_stamp_local"
     */
    public function testPropertyTimeStampLocal()
    {
    }

    /**
     * Test attribute "time_stamp_utc"
     */
    public function testPropertyTimeStampUtc()
    {
    }

    /**
     * Test attribute "top_level_item"
     */
    public function testPropertyTopLevelItem()
    {
    }

    /**
     * Test attribute "transaction_number"
     */
    public function testPropertyTransactionNumber()
    {
    }

    /**
     * Test attribute "transaction_start_time_local"
     */
    public function testPropertyTransactionStartTimeLocal()
    {
    }

    /**
     * Test attribute "transaction_start_time_uic"
     */
    public function testPropertyTransactionStartTimeUic()
    {
    }

    /**
     * Test attribute "transaction_uid"
     */
    public function testPropertyTransactionUid()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "view_id"
     */
    public function testPropertyViewId()
    {
    }

    /**
     * Test attribute "view_name"
     */
    public function testPropertyViewName()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }
}
