<?php
/**
 * QsrAutomationsDineTimeWebAheadCommandsAddWalkinCommandTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsDineTimeWebAheadCommandsAddWalkinCommandTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsDineTimeWebAheadCommandsAddWalkinCommand
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsDineTimeWebAheadCommandsAddWalkinCommandTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsDineTimeWebAheadCommandsAddWalkinCommand"
     */
    public function testQsrAutomationsDineTimeWebAheadCommandsAddWalkinCommand()
    {
    }

    /**
     * Test attribute "arrival_time"
     */
    public function testPropertyArrivalTime()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "guest"
     */
    public function testPropertyGuest()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "party_size"
     */
    public function testPropertyPartySize()
    {
    }

    /**
     * Test attribute "request_time"
     */
    public function testPropertyRequestTime()
    {
    }

    /**
     * Test attribute "site_identifier"
     */
    public function testPropertySiteIdentifier()
    {
    }

    /**
     * Test attribute "brand_uid"
     */
    public function testPropertyBrandUid()
    {
    }
}
