<?php
/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesWebAheadsIWebAheadWithSiteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QsrAutomations\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * QSR Automations API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QsrAutomations\Api;

/**
 * QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesWebAheadsIWebAheadWithSiteTest Class Doc Comment
 *
 * @category    Class */
// * @description QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesWebAheadsIWebAheadWithSite
/**
 * @package     QsrAutomations\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesWebAheadsIWebAheadWithSiteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesWebAheadsIWebAheadWithSite"
     */
    public function testQsrAutomationsEnterpriseDineTimeThirdPartyCommonBaseClassesWebAheadsIWebAheadWithSite()
    {
    }

    /**
     * Test attribute "site_uid"
     */
    public function testPropertySiteUid()
    {
    }

    /**
     * Test attribute "place_in_wait_list"
     */
    public function testPropertyPlaceInWaitList()
    {
    }

    /**
     * Test attribute "notification_type"
     */
    public function testPropertyNotificationType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "iid"
     */
    public function testPropertyIid()
    {
    }

    /**
     * Test attribute "last_update"
     */
    public function testPropertyLastUpdate()
    {
    }

    /**
     * Test attribute "server_last_update"
     */
    public function testPropertyServerLastUpdate()
    {
    }

    /**
     * Test attribute "guest"
     */
    public function testPropertyGuest()
    {
    }

    /**
     * Test attribute "guest_id"
     */
    public function testPropertyGuestId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "seated_tables"
     */
    public function testPropertySeatedTables()
    {
    }

    /**
     * Test attribute "preassigned_tables"
     */
    public function testPropertyPreassignedTables()
    {
    }

    /**
     * Test attribute "quote"
     */
    public function testPropertyQuote()
    {
    }

    /**
     * Test attribute "creation_time"
     */
    public function testPropertyCreationTime()
    {
    }

    /**
     * Test attribute "estimated_arrival_time"
     */
    public function testPropertyEstimatedArrivalTime()
    {
    }

    /**
     * Test attribute "arrival_time"
     */
    public function testPropertyArrivalTime()
    {
    }

    /**
     * Test attribute "paged_time"
     */
    public function testPropertyPagedTime()
    {
    }

    /**
     * Test attribute "seated_time"
     */
    public function testPropertySeatedTime()
    {
    }

    /**
     * Test attribute "completed_time"
     */
    public function testPropertyCompletedTime()
    {
    }

    /**
     * Test attribute "canceled_time"
     */
    public function testPropertyCanceledTime()
    {
    }

    /**
     * Test attribute "confirmation_number"
     */
    public function testPropertyConfirmationNumber()
    {
    }

    /**
     * Test attribute "seating_area_id"
     */
    public function testPropertySeatingAreaId()
    {
    }

    /**
     * Test attribute "seating_area_name"
     */
    public function testPropertySeatingAreaName()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "custom_values"
     */
    public function testPropertyCustomValues()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "party_mix"
     */
    public function testPropertyPartyMix()
    {
    }
}
